// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd/protoc-gen-gows/test/wsrpc.proto

/*
Package plugin_test is a generated protocol buffer package.

It is generated from these files:
	cmd/protoc-gen-gows/test/wsrpc.proto

It has these top-level messages:
	SimpleRequest
	SimpleResponse
*/
package plugin_test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	wsrpc "github.com/toba/wsrpc"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SimpleRequest struct {
}

func (m *SimpleRequest) Reset()                    { *m = SimpleRequest{} }
func (m *SimpleRequest) String() string            { return proto.CompactTextString(m) }
func (*SimpleRequest) ProtoMessage()               {}
func (*SimpleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SimpleResponse struct {
}

func (m *SimpleResponse) Reset()                    { *m = SimpleResponse{} }
func (m *SimpleResponse) String() string            { return proto.CompactTextString(m) }
func (*SimpleResponse) ProtoMessage()               {}
func (*SimpleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*SimpleRequest)(nil), "plugin_test.SimpleRequest")
	proto.RegisterType((*SimpleResponse)(nil), "plugin_test.SimpleResponse")
}

// Reference imports to suppress errors if not otherwise used.
var (
	_ context.Context
	_ wsrpc.Client
	_ grpc.ClientConn
)

// Server API for Test service

type TestService interface {
	Execute(context.Context) (*SimpleResponse, error)
}

func RegisterTestService(s *wsrpc.Server, srv TestService) {
	s.RegisterService(&TestServiceDescriptor, srv)
}

func TestExecuteHandler(srv interface{}, ctx context.Context, decode func(interface{}) error) (interface{}, error) {
	in := &SimpleRequest{}
	if err := decode(in); err != nil {
		return nil, err
	}
	return srv.(TestService).Execute(ctx, in)
}

var TestServiceDescriptor = wsrpc.ServiceDescriptor{
	Name:        "plugin_test.Test",
	HandlerType: (*TestService)(nil),
	Methods: []wsrpc.MethodMap{
		{
			Name:    "Execute",
			Handler: TestExecuteHandler,
		},
	},
	About: "cmd/protoc-gen-gows/test/wsrpc.proto",
}

func init() { proto.RegisterFile("cmd/protoc-gen-gows/test/wsrpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x49, 0xce, 0x4d, 0xd1,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0xd6, 0x4d, 0x4f, 0xcd, 0xd3, 0x4d, 0xcf, 0x2f, 0x2f, 0xd6,
	0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x2f, 0x2f, 0x2e, 0x2a, 0x48, 0xd6, 0x03, 0x4b, 0x09, 0x71, 0x17,
	0xe4, 0x94, 0xa6, 0x67, 0xe6, 0xc5, 0x83, 0x24, 0x94, 0xf8, 0xb9, 0x78, 0x83, 0x33, 0x73, 0x0b,
	0x72, 0x52, 0x83, 0x52, 0x0b, 0x4b, 0x41, 0x02, 0x02, 0x5c, 0x7c, 0x30, 0x81, 0xe2, 0x82, 0xfc,
	0xbc, 0xe2, 0x54, 0x23, 0x2f, 0x2e, 0x96, 0x90, 0xd4, 0xe2, 0x12, 0x21, 0x27, 0x2e, 0x76, 0xd7,
	0x8a, 0xd4, 0xe4, 0xd2, 0x92, 0x54, 0x21, 0x29, 0x3d, 0x24, 0x33, 0xf4, 0x50, 0x0c, 0x90, 0x92,
	0xc6, 0x2a, 0x07, 0x31, 0x2b, 0x89, 0x0d, 0xec, 0x04, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xf9, 0x69, 0xe7, 0xcb, 0xaa, 0x00, 0x00, 0x00,
}
